framework:
  messenger:
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          # https://github.com/symfony/redis-messenger/blob/6.3/Transport/Connection.php#L80
          auth: "%env(MESSENGER_TRANSPORT_PASS)%"
          dbindex: "%env(MESSENGER_TRANSPORT_DBINDEX)%"
          delete_after_ack: true
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: "in-memory://"
      sync: "sync://"

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
      Symfony\Component\RemoteEvent\Messenger\ConsumeRemoteEventMessage: async
